import fs from "node:fs";
import path from "node:path";
import { createHash, randomUUID } from "node:crypto";
import type { WorkspaceRecoveryCheckpointSummary, WorkspaceRecoveryEntryTarget, WorkspaceRecoveryMutationAfterInput, WorkspaceRecoveryMutationBeforeInput, WorkspaceRecoveryTurnBinding, WorkspaceRecoveryTurnSettledInput, WorkspaceRecoveryTurnStartInput } from "@piarium/extension-contract";
import type { RecoveryFileStore, RecoveryIdentity, RecoveryState, CapturedState, CaptureStateOptions } from "../recovery/journal-files.js";
import { createRecoveryFileStore, sameState } from "../recovery/journal-files.js";
import { objectPath } from "../recovery/journal-catalog.js";
import type { WorkspaceRecoveryEngine } from "../recovery/engine.js";
import type { KernelStorageAdapter, KernelStorageReference } from "./storage-adapter.js";
import type { KernelRecordResult } from "./protocol.generated.js";

type KernelRecord = KernelRecordResult;

const asObject = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const parse = <T>(record: { payloadJson: string }): T => JSON.parse(record.payloadJson) as T;

export class KernelRecoveryContentStore implements RecoveryFileStore {
  private readonly delegate: RecoveryFileStore;
  private readonly owners = new Map<string, { ownerId: string; workspaceId: string }>();
  private readonly sources = new Map<string, { workspaceId: string; recordId: string; slot: string }>();
  constructor(private readonly adapter: KernelStorageAdapter, private readonly cacheRoot: string) { this.delegate = createRecoveryFileStore(); }
  registerRecord(workspaceId: string, recordId: string, reference: KernelStorageReference): void { this.sources.set(reference.objectHash, { workspaceId, recordId, slot: reference.slot }); }
  ownerIdForHash(hash: string): string | undefined { return this.owners.get(hash)?.ownerId; }
  consumeOwner(ownerId: string): void { for (const [hash, owner] of this.owners) if (owner.ownerId === ownerId) this.owners.delete(hash); }
  private async objectBytes(workspaceId: string, hash: string): Promise<Buffer> {
    const context = await this.adapter.context(workspaceId, "recovery-catalog");
    const owner = this.owners.get(hash);
    const source = owner ? { ownerId: owner.ownerId } : (() => { const record = this.sources.get(hash); if (!record) throw new Error(`Kernel recovery object source is unknown: ${hash}`); return { recordId: record.recordId, slot: record.slot }; })();
    const chunks: Buffer[] = []; let offset = 0;
    for (;;) { const slice = await context.client.getBlob(hash, source, { offset, length: 256 * 1024 }); chunks.push(Buffer.from(slice.bytesBase64, "base64")); if (slice.eof) break; if (slice.nextOffset <= offset) throw new Error(`Kernel recovery object cursor did not advance: ${hash}`); offset = slice.nextOffset; }
    return Buffer.concat(chunks);
  }
  private async cache(workspaceId: string, state: RecoveryState): Promise<void> {
    if (state.kind !== "regular-file") return;
    const target = objectPath(this.cacheRoot, state.objectHash);
    try { if ((await fs.promises.stat(target)).size === state.byteLength) return; } catch { /* cache miss */ }
    const bytes = await this.objectBytes(workspaceId, state.objectHash);
    if (bytes.byteLength !== state.byteLength) throw new Error(`Kernel recovery object length mismatch: ${state.objectHash}`);
    await fs.promises.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
    const temporary = `${target}.tmp-${randomUUID()}`; await fs.promises.writeFile(temporary, bytes, { mode: 0o600 }); await fs.promises.rename(temporary, target).catch(async (error) => { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; await fs.promises.rm(temporary, { force: true }); });
  }
  async captureState(identity: RecoveryIdentity, root: string, inputPath: string, options: CaptureStateOptions = {}): Promise<CapturedState> {
    const captured = await this.delegate.captureState(identity, root, inputPath, { store: false });
    if (options.store !== false && captured.state.kind === "regular-file") {
      const resolved = await this.delegate.relativePathFor(identity, inputPath); const bytes = await fs.promises.readFile(resolved.absolute); const context = await this.adapter.context(identity.workspaceId, "recovery-catalog"); const stored = await context.client.putBlob(bytes, `recovery-object:${identity.workspaceId}:${captured.state.objectHash}:${randomUUID()}`); if (stored.hash !== captured.state.objectHash || stored.byteLength !== bytes.byteLength) throw new Error(`Kernel recovery object identity mismatch: ${captured.state.objectHash}`); this.owners.set(stored.hash, { ownerId: stored.ownerId, workspaceId: identity.workspaceId }); await this.cache(identity.workspaceId, captured.state);
    }
    return captured;
  }
  async applyState(identity: RecoveryIdentity, _root: string, relativePath: string, state: RecoveryState): Promise<void> { await this.cache(identity.workspaceId, state); return this.delegate.applyState(identity, this.cacheRoot, relativePath, state); }
  hashFile(filePath: string) { return this.delegate.hashFile(filePath); }
  relativePathFor(identity: RecoveryIdentity, inputPath: string) { return this.delegate.relativePathFor(identity, inputPath); }
  async verifyObject(_root: string, state: RecoveryState): Promise<void> { if (state.kind !== "regular-file") return; const source = this.sources.get(state.objectHash) ?? this.owners.get(state.objectHash); if (!source) throw new Error(`Kernel recovery object source is unknown: ${state.objectHash}`); await this.cache(source.workspaceId, state); await this.delegate.verifyObject(this.cacheRoot, state); }
}

interface RecoveryRecordInput { recordId: string; recordType: string; state: string; payload: Record<string, unknown>; references?: KernelStorageReference[]; sessionId?: string; threadId?: string; runId?: string; }

export interface KernelRecoveryContentStoreLike {
  captureState: RecoveryFileStore["captureState"];
  registerRecord(workspaceId: string, recordId: string, reference: KernelStorageReference): void;
  ownerIdForHash(hash: string): string | undefined;
  consumeOwner(ownerId: string): void;
}

export class KernelRecoveryStore {
  constructor(private readonly adapter: KernelStorageAdapter, readonly content: KernelRecoveryContentStoreLike) {}
  private async context(workspaceId: string) { return this.adapter.context(workspaceId, "recovery-catalog"); }
  private async list(workspaceId: string, recordType?: string): Promise<KernelRecord[]> { const context = await this.context(workspaceId); const rows: KernelRecord[] = []; let cursor: number | undefined; do { const page = await context.client.listRecords({ workspaceId, ...(recordType ? { recordType } : {}), ...(cursor === undefined ? {} : { cursor }), pageSize: 128 }); rows.push(...page.records); cursor = page.nextCursor === null ? undefined : page.nextCursor; } while (cursor !== undefined); for (const row of rows) for (const ref of row.references) this.content.registerRecord(workspaceId, row.recordId, ref); return rows; }
  private async put(workspaceId: string, input: RecoveryRecordInput): Promise<KernelRecord> { const context = await this.context(workspaceId); const owners = (input.references ?? []).flatMap((ref) => { const owner = this.content.ownerIdForHash(ref.objectHash); return owner ? [owner] : []; }); const stored = await context.records.put({ operationId: `recovery-direct:${workspaceId}:${input.recordId}:${createHash("sha256").update(JSON.stringify(input.payload)).update("\0").update(owners.join("\0")).digest("hex")}`, recordId: input.recordId, recordType: input.recordType, state: input.state, payloadJson: JSON.stringify(input.payload), references: input.references ?? [], ownerIds: owners, ...(input.sessionId ? { sessionId: input.sessionId } : {}), ...(input.threadId ? { threadId: input.threadId } : {}), ...(input.runId ? { runId: input.runId } : {}) }); for (const ref of stored.references) this.content.registerRecord(workspaceId, stored.recordId, ref); for (const owner of owners) this.content.consumeOwner(owner); return stored as KernelRecord; }
  private async get(workspaceId: string, recordId: string): Promise<KernelRecord | null> { const context = await this.context(workspaceId); const row = await context.records.get(recordId); if (row) for (const ref of row.references) this.content.registerRecord(workspaceId, row.recordId, ref); return row as KernelRecord | null; }
  private async release(workspaceId: string, recordId: string): Promise<void> { const context = await this.context(workspaceId); await context.records.release(`recovery-release:${workspaceId}:${recordId}:${randomUUID()}`, recordId); }
  async recordTurnStart(input: WorkspaceRecoveryTurnStartInput): Promise<WorkspaceRecoveryTurnBinding> {
    const existing = await this.get(input.workspaceId, `recovery.turn:${input.executionId}`); if (existing) return this.turn(parse(existing));
    const checkpoints = await this.list(input.workspaceId, "recovery.checkpoint"); const sequence = Math.max(0, ...checkpoints.map((row) => Number(asObject(parse(row)).sequence ?? 0))) + 1; const checkpointId = `recovery.checkpoint:${input.workspaceId}:${input.executionId}`; const checkpoint = { id: checkpointId, workspaceId: input.workspaceId, sequence, source: "turn", state: input.failure ? "incomplete" : "pending", createdAt: new Date().toISOString(), sessionId: input.sessionId, entryId: input.userEntryId, executionId: input.executionId, changedPathCount: 0, byteLength: 0 }; await this.put(input.workspaceId, { recordId: checkpointId, recordType: "recovery.checkpoint", state: String(checkpoint.state), payload: checkpoint, sessionId: input.sessionId }); const binding = { ...input, checkpointId, runtimeKey: `${input.workerId}@${input.runtimeGeneration}`, status: input.failure ? "incomplete" : "pending", startedAt: checkpoint.createdAt, unrecordedResourceIds: [] } as unknown as WorkspaceRecoveryTurnBinding; await this.put(input.workspaceId, { recordId: `recovery.turn:${input.executionId}`, recordType: "recovery.turn", state: String(binding.status), payload: { ...binding } as Record<string, unknown>, sessionId: input.sessionId }); return binding;
  }
  private turn(payload: Record<string, unknown>): WorkspaceRecoveryTurnBinding { return { activeWriterScopes: Array.isArray(payload.activeWriterScopes) ? payload.activeWriterScopes as string[] : [], checkpointId: String(payload.checkpointId), executionId: String(payload.executionId), provenance: payload.provenance as WorkspaceRecoveryTurnBinding["provenance"], runtimeGeneration: Number(payload.runtimeGeneration), runtimeKey: String(payload.runtimeKey), sessionId: String(payload.sessionId), startedAt: String(payload.startedAt), status: payload.status as WorkspaceRecoveryTurnBinding["status"], unrecordedResourceIds: Array.isArray(payload.unrecordedResourceIds) ? payload.unrecordedResourceIds as string[] : [], userEntryId: String(payload.userEntryId), workerId: String(payload.workerId), workspaceId: String(payload.workspaceId), ...(typeof payload.assistantEntryId === "string" ? { assistantEntryId: payload.assistantEntryId } : {}), ...(typeof payload.settledAt === "string" ? { settledAt: payload.settledAt } : {}) };
  }
  async listCheckpoints(workspaceId: string): Promise<WorkspaceRecoveryCheckpointSummary[]> { return (await this.list(workspaceId, "recovery.checkpoint")).map((row) => { const p = asObject(parse(row)); return { id: String(p.id), workspaceId: String(p.workspaceId), sequence: Number(p.sequence), source: p.source as WorkspaceRecoveryCheckpointSummary["source"], state: p.state as WorkspaceRecoveryCheckpointSummary["state"], createdAt: String(p.createdAt), ...(typeof p.label === "string" ? { label: p.label } : {}), ...(typeof p.sessionId === "string" ? { sessionId: p.sessionId } : {}), ...(typeof p.entryId === "string" ? { entryId: p.entryId } : {}), ...(typeof p.executionId === "string" ? { executionId: p.executionId } : {}), changedPathCount: Number(p.changedPathCount ?? 0), byteLength: Number(p.byteLength ?? 0) }; }).sort((a, b) => b.sequence - a.sequence); }
  async createNamedCheckpoint(workspaceId: string, name: string): Promise<WorkspaceRecoveryCheckpointSummary> { const checkpoints = await this.listCheckpoints(workspaceId); const sequence = Math.max(0, ...checkpoints.map((item) => item.sequence)) + 1; const summary: WorkspaceRecoveryCheckpointSummary = { id: `recovery.checkpoint:${workspaceId}:named:${randomUUID()}`, workspaceId, sequence, source: "named", state: "ready", createdAt: new Date().toISOString(), label: name, changedPathCount: 0, byteLength: 0 }; await this.put(workspaceId, { recordId: summary.id, recordType: "recovery.checkpoint", state: "ready", payload: { ...summary } as Record<string, unknown> }); return summary; }
  async resolveEntry(input: WorkspaceRecoveryEntryTarget): Promise<Record<string, unknown>> { const turns = await this.list(input.workspaceId, "recovery.turn"); const row = turns.find((record) => { const payload = asObject(parse(record)); return payload.sessionId === input.sessionId && (payload.userEntryId === input.entryId || payload.assistantEntryId === input.entryId); }); if (!row) return { status: "unbound", reason: "entry-unbound" }; const binding = this.turn(parse(row)); const checkpoint = (await this.listCheckpoints(input.workspaceId)).find((item) => item.id === binding.checkpointId); if (!checkpoint || checkpoint.state !== "ready" || binding.status !== "ready") return { status: "incomplete", reason: "checkpoint-incomplete", binding, ...(checkpoint ? { checkpoint } : {}) }; return { status: "ready", binding, checkpoint, position: binding.userEntryId === input.entryId ? "before" : "after" }; }
  async recordMutationBefore(input: WorkspaceRecoveryMutationBeforeInput): Promise<boolean> { const turn = await this.get(input.workspaceId, `recovery.turn:${input.executionId}`); if (!turn) return false; const binding = this.turn(parse(turn)); const captured = await this.content.captureState({ authorityId: "kernel", canonicalRoot: (await this.adapter.context(input.workspaceId, "recovery-catalog")).identity.canonicalRoot, filesystemProfile: process.platform === "win32" ? "windows-local" : `${process.platform}-local`, workspaceId: input.workspaceId }, (await this.adapter.context(input.workspaceId, "recovery-catalog")).root, input.path, { store: true }); const id = `recovery.change:${input.workspaceId}:${binding.checkpointId}:${captured.path}`; if (await this.get(input.workspaceId, id)) return true; const refs = captured.state.kind === "regular-file" ? [{ slot: "before", objectHash: captured.state.objectHash }] : []; await this.put(input.workspaceId, { recordId: id, recordType: "recovery.change", state: "before", payload: { ...input, checkpointId: binding.checkpointId, path: captured.path, before: captured.state }, references: refs }); return true; }
  async recordMutationAfter(input: WorkspaceRecoveryMutationAfterInput): Promise<boolean> { const turn = await this.get(input.workspaceId, `recovery.turn:${input.executionId}`); if (!turn) return false; const binding = this.turn(parse(turn)); const captured = await this.content.captureState({ authorityId: "kernel", canonicalRoot: (await this.adapter.context(input.workspaceId, "recovery-catalog")).identity.canonicalRoot, filesystemProfile: process.platform === "win32" ? "windows-local" : `${process.platform}-local`, workspaceId: input.workspaceId }, (await this.adapter.context(input.workspaceId, "recovery-catalog")).root, input.path, { store: true }); const id = `recovery.change:${input.workspaceId}:${binding.checkpointId}:${captured.path}`; const prior = await this.get(input.workspaceId, id); if (!prior) return false; const payload = asObject(parse(prior)); const before = payload.before as RecoveryState; if (sameState(before, captured.state)) { await this.release(input.workspaceId, id); return false; } const refs = [ ...(before.kind === "regular-file" ? [{ slot: "before", objectHash: before.objectHash }] : []), ...(captured.state.kind === "regular-file" ? [{ slot: "after", objectHash: captured.state.objectHash }] : []) ]; await this.put(input.workspaceId, { recordId: id, recordType: "recovery.change", state: input.succeeded ? "after" : "failed", payload: { ...payload, ...input, after: captured.state }, references: refs }); return true; }
  async recordTurnSettled(input: WorkspaceRecoveryTurnSettledInput): Promise<WorkspaceRecoveryTurnBinding> { const row = await this.get(input.workspaceId, `recovery.turn:${input.executionId}`); if (!row) throw new Error("checkpoint-missing"); const binding = this.turn(parse(row)); const changes = await this.list(input.workspaceId, "recovery.change"); const recorded = changes.filter((change) => { const p = asObject(parse(change)); return p.executionId === input.executionId; }).map((change) => String(asObject(parse(change)).path)); const observed = [...new Set(input.observedResourceIds)]; const unrecorded = observed.filter((path) => !recorded.includes(path)); const exact = !input.failure && input.observationComplete && unrecorded.length === 0; const settled = { ...binding, ...input, status: (exact ? "ready" : "incomplete") as WorkspaceRecoveryTurnBinding["status"], settledAt: new Date().toISOString(), unrecordedResourceIds: unrecorded }; await this.put(input.workspaceId, { recordId: `recovery.turn:${input.executionId}`, recordType: "recovery.turn", state: String(settled.status), payload: { ...settled } as Record<string, unknown>, sessionId: binding.sessionId }); const checkpoint = await this.get(input.workspaceId, binding.checkpointId); if (checkpoint) { const payload = asObject(parse(checkpoint)); await this.put(input.workspaceId, { recordId: checkpoint.recordId, recordType: "recovery.checkpoint", state: String(settled.status), payload: { ...payload, state: settled.status }, sessionId: binding.sessionId }); } return settled; }
}

export const createKernelRecoveryDirectFacade = (base: WorkspaceRecoveryEngine, store: KernelRecoveryStore): WorkspaceRecoveryEngine => {
  const facade = { ...base } as WorkspaceRecoveryEngine;
  facade.recordTurnStart = async (input) => ({ binding: await store.recordTurnStart(input), status: "ready" });
  facade.recordMutationBefore = async (input) => ({ recorded: await store.recordMutationBefore(input), status: "ready" });
  facade.recordMutationAfter = async (input) => ({ recorded: await store.recordMutationAfter(input), status: "ready" });
  facade.recordTurnSettled = async (input) => ({ binding: await store.recordTurnSettled(input), status: "ready" });
  facade.createCheckpoint = async (input) => ({ checkpoint: await store.createNamedCheckpoint(input.workspaceId, input.name), status: "ready" });
  facade.listCheckpoints = async (input) => { const checkpoints = await store.listCheckpoints(input.workspaceId); const start = input.cursor === undefined ? 0 : checkpoints.findIndex((item) => item.sequence < input.cursor!); const page = checkpoints.slice(Math.max(0, start), input.limit === undefined ? undefined : Math.max(0, start) + input.limit); return { page: { checkpoints: page, nextCursor: page.length && page.length < checkpoints.length ? page.at(-1)!.sequence : null }, status: "ready" }; };
  facade.resolveEntry = async (input) => store.resolveEntry(input) as never;
  return facade;
};
