import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { WorkspaceRecoveryCheckpointSummary, WorkspaceRecoveryEntryTarget, WorkspaceRecoveryMutationAfterInput, WorkspaceRecoveryMutationBeforeInput, WorkspaceRecoveryTurnBinding, WorkspaceRecoveryTurnSettledInput, WorkspaceRecoveryTurnStartInput } from "@piarium/extension-contract";
import type { RecoveryFileStore, RecoveryIdentity, RecoveryState, CapturedState, CaptureStateOptions } from "../recovery/journal-files.js";
import { createRecoveryFileStore, sameState } from "../recovery/journal-files.js";
import { objectPath } from "../recovery/object-path.js";
import type { WorkspaceRecoveryEngine } from "../recovery/engine.js";
import type { KernelStorageAdapter, KernelStorageReference } from "./storage-adapter.js";
const asObject = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};

export class KernelRecoveryContentStore implements RecoveryFileStore {
  private readonly delegate: RecoveryFileStore;
  private readonly owners = new Map<string, { ownerId: string; workspaceId: string }>();
  private readonly sources = new Map<string, { workspaceId: string; recordId: string; slot: string }>();
  constructor(private readonly adapter: KernelStorageAdapter, private readonly cacheRoot: string) { this.delegate = createRecoveryFileStore(); }
  registerRecord(workspaceId: string, recordId: string, reference: KernelStorageReference): void { this.sources.set(reference.objectHash, { workspaceId, recordId, slot: reference.slot }); }
  ownerIdForHash(hash: string): string | undefined { return this.owners.get(hash)?.ownerId; }
  consumeOwner(ownerId: string): void { for (const [hash, owner] of this.owners) if (owner.ownerId === ownerId) this.owners.delete(hash); }
  private async objectBytes(workspaceId: string, hash: string, sessionId?: string): Promise<Buffer> {
    const context = await this.adapter.context(workspaceId, sessionId ? "recovery-actor" : "recovery-catalog", sessionId ? { owningWorkspace: workspaceId, executionWorkspace: workspaceId, sessionId, pathScopes: [""] } : undefined);
    const owner = this.owners.get(hash);
    const source = owner ? { ownerId: owner.ownerId } : (() => { const record = this.sources.get(hash); if (!record) throw new Error(`Kernel recovery object source is unknown: ${hash}`); return { recordId: record.recordId, slot: record.slot }; })();
    const chunks: Buffer[] = []; let offset = 0;
    for (;;) { const slice = await context.client.getBlob(hash, source, { offset, length: 256 * 1024 }); chunks.push(Buffer.from(slice.bytesBase64, "base64")); if (slice.eof) break; if (slice.nextOffset <= offset) throw new Error(`Kernel recovery object cursor did not advance: ${hash}`); offset = slice.nextOffset; }
    return Buffer.concat(chunks);
  }
  private async cache(workspaceId: string, state: RecoveryState, sessionId?: string): Promise<void> {
    if (state.kind !== "regular-file") return;
    const target = objectPath(this.cacheRoot, state.objectHash);
    try { if ((await fs.promises.stat(target)).size === state.byteLength) return; } catch { /* cache miss */ }
    const bytes = await this.objectBytes(workspaceId, state.objectHash, sessionId);
    if (bytes.byteLength !== state.byteLength) throw new Error(`Kernel recovery object length mismatch: ${state.objectHash}`);
    await fs.promises.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
    const temporary = `${target}.tmp-${randomUUID()}`; await fs.promises.writeFile(temporary, bytes, { mode: 0o600 }); await fs.promises.rename(temporary, target).catch(async (error) => { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; await fs.promises.rm(temporary, { force: true }); });
  }
  async captureState(identity: RecoveryIdentity, root: string, inputPath: string, options: CaptureStateOptions = {}, sessionId?: string): Promise<CapturedState> {
    const captured = await this.delegate.captureState(identity, root, inputPath, { store: false });
    if (options.store !== false && captured.state.kind === "regular-file") {
      const resolved = await this.delegate.relativePathFor(identity, inputPath); const bytes = await fs.promises.readFile(resolved.absolute); const context = await this.adapter.context(identity.workspaceId, sessionId ? "recovery-actor" : "recovery-catalog", sessionId ? { owningWorkspace: identity.workspaceId, executionWorkspace: identity.workspaceId, sessionId, pathScopes: [""] } : undefined); const stored = await context.client.putBlob(bytes, `recovery-object:${identity.workspaceId}:${captured.state.objectHash}:${randomUUID()}`); if (stored.hash !== captured.state.objectHash || stored.byteLength !== bytes.byteLength) throw new Error(`Kernel recovery object identity mismatch: ${captured.state.objectHash}`); this.owners.set(stored.hash, { ownerId: stored.ownerId, workspaceId: identity.workspaceId }); await this.cache(identity.workspaceId, captured.state, sessionId);
    }
    return captured;
  }
  async applyState(identity: RecoveryIdentity, _root: string, relativePath: string, state: RecoveryState): Promise<void> { await this.cache(identity.workspaceId, state); return this.delegate.applyState(identity, this.cacheRoot, relativePath, state); }
  hashFile(filePath: string) { return this.delegate.hashFile(filePath); }
  relativePathFor(identity: RecoveryIdentity, inputPath: string) { return this.delegate.relativePathFor(identity, inputPath); }
  async verifyObject(_root: string, state: RecoveryState): Promise<void> { if (state.kind !== "regular-file") return; const source = this.sources.get(state.objectHash) ?? this.owners.get(state.objectHash); if (!source) throw new Error(`Kernel recovery object source is unknown: ${state.objectHash}`); await this.cache(source.workspaceId, state); await this.delegate.verifyObject(this.cacheRoot, state); }
}

export interface KernelRecoveryContentStoreLike {
  captureState: (identity: RecoveryIdentity, root: string, inputPath: string, options?: CaptureStateOptions, sessionId?: string) => Promise<CapturedState>;
  registerRecord(workspaceId: string, recordId: string, reference: KernelStorageReference): void;
  ownerIdForHash(hash: string): string | undefined;
  consumeOwner(ownerId: string): void;
}

export class KernelRecoveryStore {
  constructor(private readonly adapter: KernelStorageAdapter, readonly content: KernelRecoveryContentStoreLike) {}
  private actor(workspaceId: string, sessionId?: string) { return { owningWorkspace: workspaceId, executionWorkspace: workspaceId, ...(sessionId ? { sessionId } : {}), pathScopes: [""] }; }
  private async context(workspaceId: string, sessionId?: string, maintenance = false) { return this.adapter.context(workspaceId, maintenance ? "recovery-maintenance" : "recovery-actor", maintenance ? { owningWorkspace: workspaceId, executionWorkspace: workspaceId, pathScopes: [""], capabilities: ["recovery.maintenance", "storage.gc"] } : this.actor(workspaceId, sessionId)); }
  private summary(value: Record<string, unknown>): WorkspaceRecoveryCheckpointSummary { return { id: String(value.id), workspaceId: String(value.workspaceId), sequence: Number(value.sequence), source: value.source as WorkspaceRecoveryCheckpointSummary["source"], state: value.state as WorkspaceRecoveryCheckpointSummary["state"], createdAt: String(value.createdAt), ...(typeof value.label === "string" ? { label: value.label } : {}), ...(typeof value.sessionId === "string" ? { sessionId: value.sessionId } : {}), ...(typeof value.entryId === "string" ? { entryId: value.entryId } : {}), ...(typeof value.executionId === "string" ? { executionId: value.executionId } : {}), changedPathCount: Number(value.changedPathCount ?? 0), byteLength: Number(value.byteLength ?? 0) }; }
  async recordTurnStart(input: WorkspaceRecoveryTurnStartInput): Promise<WorkspaceRecoveryTurnBinding> {
    const context = await this.context(input.workspaceId, input.sessionId);
    const value = await context.client.recoveryTurnStart({ operationId: `recovery-turn-start:${input.workspaceId}:${input.executionId}`, workspaceId: input.workspaceId, executionId: input.executionId, sessionId: input.sessionId, userEntryId: input.userEntryId, workerId: input.workerId, runtimeGeneration: input.runtimeGeneration, activeWriterScopes: [...input.activeWriterScopes], provenance: input.provenance, ...(input.failure === undefined ? {} : { failure: Boolean(input.failure) }) });
    return this.turn(value);
  }
  private turn(payload: Record<string, unknown>): WorkspaceRecoveryTurnBinding { return { activeWriterScopes: Array.isArray(payload.activeWriterScopes) ? payload.activeWriterScopes as string[] : [], checkpointId: String(payload.checkpointId), executionId: String(payload.executionId), provenance: payload.provenance as WorkspaceRecoveryTurnBinding["provenance"], runtimeGeneration: Number(payload.runtimeGeneration), runtimeKey: String(payload.runtimeKey), sessionId: String(payload.sessionId), startedAt: String(payload.startedAt), status: payload.status as WorkspaceRecoveryTurnBinding["status"], unrecordedResourceIds: Array.isArray(payload.unrecordedResourceIds) ? payload.unrecordedResourceIds as string[] : [], userEntryId: String(payload.userEntryId), workerId: String(payload.workerId), workspaceId: String(payload.workspaceId), ...(typeof payload.assistantEntryId === "string" ? { assistantEntryId: payload.assistantEntryId } : {}), ...(typeof payload.settledAt === "string" ? { settledAt: payload.settledAt } : {}) };
  }
  async listCheckpoints(workspaceId: string): Promise<WorkspaceRecoveryCheckpointSummary[]> { const context = await this.context(workspaceId, undefined, true); const result: WorkspaceRecoveryCheckpointSummary[] = []; let cursor: number | undefined; do { const value = await context.client.recoveryCheckpointList({ workspaceId, pageSize: 512, ...(cursor === undefined ? {} : { cursor }) }); if (Array.isArray(value.checkpoints)) result.push(...value.checkpoints.map((item) => this.summary(asObject(item)))); cursor = typeof value.nextCursor === "number" ? value.nextCursor : undefined; } while (cursor !== undefined); return result.sort((a, b) => b.sequence - a.sequence); }
  async createNamedCheckpoint(workspaceId: string, name: string): Promise<WorkspaceRecoveryCheckpointSummary> { const context = await this.context(workspaceId, undefined, true); return this.summary(await context.client.recoveryCheckpointCreate({ operationId: `recovery-checkpoint:${workspaceId}:${randomUUID()}`, workspaceId, label: name })); }
  async resolveEntry(input: WorkspaceRecoveryEntryTarget): Promise<Record<string, unknown>> { const context = await this.context(input.workspaceId, input.sessionId); const value = await context.client.recoveryEntryResolve({ workspaceId: input.workspaceId, sessionId: input.sessionId, entryId: input.entryId }); if (typeof value.executionId !== "string") return value; const turn = await context.client.recoveryTurnGet({ workspaceId: input.workspaceId, executionId: value.executionId }); const binding = turn ? this.turn(turn) : undefined; const checkpointValue = value.checkpoint; const checkpoint = checkpointValue && typeof checkpointValue === "object" ? this.summary(asObject(checkpointValue)) : undefined; return { ...value, ...(binding ? { binding } : {}), ...(checkpoint ? { checkpoint } : {}) }; }
  async recordMutationBefore(input: WorkspaceRecoveryMutationBeforeInput): Promise<boolean> { const lookup = await this.context(input.workspaceId, undefined, true); const turn = await lookup.client.recoveryTurnGet({ workspaceId: input.workspaceId, executionId: input.executionId }); if (!turn) return false; const sessionId = typeof turn.sessionId === "string" ? turn.sessionId : undefined; const context = await this.context(input.workspaceId, sessionId); const captured = await this.content.captureState({ authorityId: "kernel", canonicalRoot: context.identity.canonicalRoot, filesystemProfile: process.platform === "win32" ? "windows-local" : `${process.platform}-local`, workspaceId: input.workspaceId }, context.root, input.path, { store: true }, sessionId); const ownerId = captured.state.kind === "regular-file" ? this.content.ownerIdForHash(captured.state.objectHash) : undefined; const refs = captured.state.kind === "regular-file" ? [{ slot: "before", objectHash: captured.state.objectHash, ...(ownerId ? { ownerId } : {}) }] : []; if (captured.state.kind === "regular-file") this.content.registerRecord(input.workspaceId, `change:${String(turn.checkpointId)}:${captured.path}`, refs[0]!); await context.client.recoveryChangeBefore({ operationId: `recovery-before:${input.executionId}:${captured.path}`, workspaceId: input.workspaceId, executionId: input.executionId, checkpointId: String(turn.checkpointId), path: captured.path, toolName: input.toolName, mutationId: input.mutationId, beforeJson: JSON.stringify(captured.state), references: refs }); return true; }
  async recordMutationAfter(input: WorkspaceRecoveryMutationAfterInput): Promise<boolean> { const lookup = await this.context(input.workspaceId, undefined, true); const turn = await lookup.client.recoveryTurnGet({ workspaceId: input.workspaceId, executionId: input.executionId }); if (!turn) return false; const sessionId = typeof turn.sessionId === "string" ? turn.sessionId : undefined; const context = await this.context(input.workspaceId, sessionId); const checkpointId = String(turn.checkpointId); const captured = await this.content.captureState({ authorityId: "kernel", canonicalRoot: context.identity.canonicalRoot, filesystemProfile: process.platform === "win32" ? "windows-local" : `${process.platform}-local`, workspaceId: input.workspaceId }, context.root, input.path, { store: true }, sessionId); const capturedOwner = captured.state.kind === "regular-file" ? this.content.ownerIdForHash(captured.state.objectHash) : undefined; const prior = await context.client.recoveryChangeGet({ workspaceId: input.workspaceId, checkpointId, path: captured.path }); if (!prior) { if (capturedOwner) await context.client.releaseBlob(capturedOwner).catch(() => undefined); return false; } const before = asObject(prior.before) as unknown as RecoveryState; if (sameState(before, captured.state)) { await context.client.recoveryChangeAfter({ operationId: `recovery-after:${input.executionId}:${captured.path}`, workspaceId: input.workspaceId, executionId: input.executionId, checkpointId, path: captured.path, afterJson: JSON.stringify(captured.state), succeeded: false, expectedRevision: Number(prior.revision), references: [] }); if (capturedOwner) await context.client.releaseBlob(capturedOwner).catch(() => undefined); return false; } const refs = [ ...(before.kind === "regular-file" ? [{ slot: "before", objectHash: before.objectHash }] : []), ...(captured.state.kind === "regular-file" ? [{ slot: "after", objectHash: captured.state.objectHash, ...(capturedOwner ? { ownerId: capturedOwner } : {}) }] : []) ]; await context.client.recoveryChangeAfter({ operationId: `recovery-after:${input.executionId}:${captured.path}`, workspaceId: input.workspaceId, executionId: input.executionId, checkpointId, path: captured.path, afterJson: JSON.stringify(captured.state), succeeded: input.succeeded, expectedRevision: Number(prior.revision), references: refs }); return true; }
  async recordTurnSettled(input: WorkspaceRecoveryTurnSettledInput): Promise<WorkspaceRecoveryTurnBinding> { const lookup = await this.context(input.workspaceId, undefined, true); const row = await lookup.client.recoveryTurnGet({ workspaceId: input.workspaceId, executionId: input.executionId }); if (!row) throw new Error("checkpoint-missing"); const context = await this.context(input.workspaceId, typeof row.sessionId === "string" ? row.sessionId : undefined); const settled = await context.client.recoveryTurnSettle({ operationId: `recovery-settle:${input.executionId}`, workspaceId: input.workspaceId, executionId: input.executionId, expectedRevision: Number(row.revision), status: input.failure || !input.observationComplete ? "incomplete" : "ready", observedResourceIds: [...new Set(input.observedResourceIds)], observationComplete: input.observationComplete, ...(input.assistantEntryId ? { assistantEntryId: input.assistantEntryId } : {}), ...(input.failure ? { failureJson: JSON.stringify(input.failure) } : {}) }); return this.turn(settled); }
  private stateReferences(value: unknown, prefix: string): Array<{ slot: string; objectHash: string }> { const output: Array<{ slot: string; objectHash: string }> = []; const visit = (entry: unknown, slot: string): void => { if (!entry || typeof entry !== "object") return; if (Array.isArray(entry)) { entry.forEach((child, index) => visit(child, `${slot}[${index}]`)); return; } const record = entry as Record<string, unknown>; if (typeof record.objectHash === "string" && /^sha256-[0-9a-f]{64}$/u.test(record.objectHash)) output.push({ slot, objectHash: record.objectHash }); for (const [key, child] of Object.entries(record)) if (key !== "objectHash") visit(child, slot ? `${slot}.${key}` : key); }; visit(value, prefix); return output; }
  async createOperation(input: { operationId: string; workspaceId: string; kind: string; state: string; data: Record<string, unknown>; targets: Record<string, { expected?: RecoveryState; target?: RecoveryState; safety?: RecoveryState }>; sessionId?: string }): Promise<Record<string, unknown>> { const context = await this.context(input.workspaceId, input.sessionId); const files = Object.entries(input.targets).map(([path, states]) => ({ path, ...(states.expected ? { expectedJson: JSON.stringify(states.expected) } : {}), ...(states.target ? { targetJson: JSON.stringify(states.target) } : {}), ...(states.safety ? { safetyJson: JSON.stringify(states.safety) } : {}), phase: "pending", references: this.stateReferences(states, path) })); return context.client.recoveryOperationCreate({ operationId: input.operationId, workspaceId: input.workspaceId, kind: input.kind, state: input.state, dataJson: JSON.stringify(input.data), files }); }
  async updateOperationFile(input: { operationId: string; workspaceId: string; path: string; expectedRevision: number; expectedPhase: string; phase: string; observedFingerprint?: string; expected?: RecoveryState; target?: RecoveryState; safety?: RecoveryState; sessionId?: string }): Promise<Record<string, unknown>> { const context = await this.context(input.workspaceId, input.sessionId); return context.client.recoveryOperationFileCas({ operationId: input.operationId, workspaceId: input.workspaceId, path: input.path, expectedRevision: input.expectedRevision, expectedPhase: input.expectedPhase, phase: input.phase, ...(input.observedFingerprint ? { observedFingerprint: input.observedFingerprint } : {}), ...(input.expected ? { expectedJson: JSON.stringify(input.expected) } : {}), ...(input.target ? { targetJson: JSON.stringify(input.target) } : {}), ...(input.safety ? { safetyJson: JSON.stringify(input.safety) } : {}), ...(input.expected || input.target || input.safety ? { references: this.stateReferences({ expected: input.expected, target: input.target, safety: input.safety }, input.path) } : {}) }); }
  async completeOperation(input: { operationId: string; workspaceId: string; expectedRevision: number; state: string; result?: Record<string, unknown>; failure?: Record<string, unknown>; sessionId?: string }): Promise<Record<string, unknown>> { const context = await this.context(input.workspaceId, input.sessionId); return context.client.recoveryOperationComplete({ operationId: input.operationId, workspaceId: input.workspaceId, expectedRevision: input.expectedRevision, state: input.state, ...(input.result ? { resultJson: JSON.stringify(input.result) } : {}), ...(input.failure ? { failureJson: JSON.stringify(input.failure) } : {}) }); }
  async getOperation(workspaceId: string, operationId: string, sessionId?: string): Promise<Record<string, unknown> | null> { const context = await this.context(workspaceId, sessionId, !sessionId); return context.client.getRecovery({ operationId }); }
  async listOperations(workspaceId: string, kind?: string): Promise<Record<string, unknown>[]> { const context = await this.context(workspaceId, undefined, true); const value = await context.client.recoveryOperationList({ workspaceId, ...(kind ? { kind } : {}), pageSize: 512 }); return Array.isArray(value.operations) ? value.operations.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object") : []; }
  async releaseOperation(workspaceId: string, operationId: string): Promise<Record<string, unknown>> { const context = await this.context(workspaceId, undefined, true); return context.client.recoveryOperationRelease({ operationId, workspaceId }); }
}

export const createKernelRecoveryDirectFacade = (base: WorkspaceRecoveryEngine, store: KernelRecoveryStore): WorkspaceRecoveryEngine => {
  const facade = { ...base } as WorkspaceRecoveryEngine;
  facade.recordTurnStart = async (input) => ({ binding: await store.recordTurnStart(input), status: "ready" });
  facade.recordMutationBefore = async (input) => ({ recorded: await store.recordMutationBefore(input), status: "ready" });
  facade.recordMutationAfter = async (input) => ({ recorded: await store.recordMutationAfter(input), status: "ready" });
  facade.recordTurnSettled = async (input) => ({ binding: await store.recordTurnSettled(input), status: "ready" });
  facade.createCheckpoint = async (input) => ({ checkpoint: await store.createNamedCheckpoint(input.workspaceId, input.name), status: "ready" });
  facade.listCheckpoints = async (input) => { const checkpoints = await store.listCheckpoints(input.workspaceId); const start = input.cursor === undefined ? 0 : checkpoints.findIndex((item) => item.sequence < input.cursor!); const page = checkpoints.slice(Math.max(0, start), input.limit === undefined ? undefined : Math.max(0, start) + input.limit); return { page: { checkpoints: page, nextCursor: page.length && page.length < checkpoints.length ? page.at(-1)!.sequence : null }, status: "ready" }; };
  facade.resolveEntry = async (input) => store.resolveEntry(input) as never;
  return facade;
};
