import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import { PIARIUM_BUILTIN_TRANSITION_SCENE_EXTENSION } from '@piarium/extension-builtins';
import {
  PIARIUM_WORKBENCH_PROFILE_TRANSITION_SCENE,
  parsePiariumTransitionSceneContributionData,
  piariumTransitionSceneDuration,
} from '@piarium/extension-contract';
import { LOGO_GRID_SIZE } from './piarium-logo-geometry';
import {
  buildAdaptiveSplashTiles,
  mountSplashTileCanvas,
  splashGroundScript,
} from './piarium-splash-canvas';
import { splashCubeMarkup } from './piarium-splash-cube';
import {
  CAMERA_FLAT_FLOOR_TRANSFORM,
  CAMERA_FLOOR_TRANSFORM,
  CAMERA_PRESS_FLOOR_TRANSFORM,
  HORIZON_RISE_PX,
  SPLASH_CAMERA_DISTANCE_PX,
  SPLASH_CAMERA_PRESS_TILT_DEG,
  SPLASH_CAMERA_SPIN_DEG,
  SPLASH_CAMERA_TILT_DEG,
  cameraDepth,
  floorInscribedRadius,
  floorReach,
  projectFlatFloorPoint,
  projectPoint,
} from './piarium-splash-camera';
import {
  CUBE_EDGE_PX,
  GROUND_EDGE_RISE_PX,
  GROUND_FADE_RISE_PX,
  GROUND_REACH,
  GROUND_REVEAL_RADIUS_PX,
  GROUND_SHAPE,
  PIARIUM_SPLASH_STYLE_ELEMENT_ID,
  PIARIUM_SPLASH_COLORS,
  SPLASH_GROUND_ORIGIN_Y_PCT,
  SPLASH_GROUND_VISIBLE_FAR_RISE_PX,
  SPLASH_EXIT_DURATION_MS,
  SPLASH_REDUCED_EXIT_DURATION_MS,
  SPLASH_WORKBENCH_QUICK_DURATION_MS,
  splashPlaneCss,
  splashTilePlaybackTiming,
  splashWorkbenchTileDelays,
  splashWorkbenchPhaseDurationMs,
} from './piarium-splash-lattice';
import { INITIAL_SPLASH_IDS } from '@/lib/splash';

/**
 * What these tests are for.
 *
 * Three earlier versions of this splash looked wrong for a reason no test would have caught, because
 * nothing asserted a relationship between the cube and the floor it was supposed to stand on. Each time
 * the floor was drawn with one set of numbers and the cube with another, and each time it read as a cube
 * hovering in front of a pattern. So these assert relationships, not appearance: that the projection
 * really converges, that the cube's base is one floor cell, that the floor and cube share one camera, and
 * that the four hosts that paint this splash still carry the same generated bytes.
 */

const repoRoot = path.resolve(import.meta.dirname, '..', '..', '..', '..', '..');
const readRepoFile = (...segments: string[]): string =>
  readFileSync(path.join(repoRoot, ...segments), 'utf8');

const readWebShell = (): string => readRepoFile('packages', 'web', 'index.html');
const readMiniChat = (): string => readRepoFile('packages', 'web', 'mini-chat.html');
const readWebview = (): string => readRepoFile('packages', 'vscode', 'src', 'webviewHtml.ts');

const buildField = (
  viewportWidth = 1920,
  viewportHeight = 1080,
  overrides: Partial<Parameters<typeof buildAdaptiveSplashTiles>[0]> = {},
) => buildAdaptiveSplashTiles({
  breatheShare: 0,
  cameraDistancePx: SPLASH_CAMERA_DISTANCE_PX,
  cameraSpinDeg: SPLASH_CAMERA_SPIN_DEG,
  cameraTiltDeg: SPLASH_CAMERA_TILT_DEG,
  cellPx: CUBE_EDGE_PX,
  direction: 'forward',
  mode: 'boot',
  originYPct: SPLASH_GROUND_ORIGIN_Y_PCT,
  randomSeed: 0x02f6e2b1,
  viewportHeight,
  viewportWidth,
  visibleFarRisePx: SPLASH_GROUND_VISIBLE_FAR_RISE_PX,
  ...overrides,
});

/** Content a host embeds verbatim between a pair of sentinels. */
const between = (body: string, open: string, close: string): string => {
  const start = body.indexOf(open);
  const end = body.indexOf(close, start);
  expect(start, `${open} missing`).toBeGreaterThan(-1);
  expect(end, `${close} missing`).toBeGreaterThan(start);
  return body.slice(start + open.length, end).trim();
};

const CSS_SENTINELS = ['/* SPLASH-CSS-BEGIN */', '/* SPLASH-CSS-END */'] as const;
const JS_SENTINELS = ['/* SPLASH-JS-BEGIN */', '/* SPLASH-JS-END */'] as const;
const MARK_SENTINELS = ['<!-- SPLASH-MARK-BEGIN -->', '<!-- SPLASH-MARK-END -->'] as const;

describe('the camera is a perspective camera', () => {
  test('equal steps away from the viewer project to shrinking steps on screen', () => {
    // The property isometric could never have. Without it there is no vanishing point, no size gradient,
    // and nothing to tell the eye whether the plane recedes or tilts up toward it.
    const step = (n: number): number => {
      const near = projectPoint({ x: -n * CUBE_EDGE_PX, y: -n * CUBE_EDGE_PX, z: 0 });
      const far = projectPoint({ x: -(n + 1) * CUBE_EDGE_PX, y: -(n + 1) * CUBE_EDGE_PX, z: 0 });
      return near.y - far.y;
    };

    const steps = [0, 1, 2, 4, 8, 14].map(step);
    for (const [index, value] of steps.entries()) {
      expect(value).toBeGreaterThan(0);
      if (index > 0) expect(value).toBeLessThan(steps[index - 1] as number);
    }
    // Not a token amount of convergence: even after lifting the camera, the far rows are less than a
    // third the depth of the near ones.
    expect(steps.at(-1) as number).toBeLessThan((steps[0] as number) / 3);
  });

  test('the floor origin projects to the origin, so the two coordinate systems share a point', () => {
    expect(projectPoint({ x: 0, y: 0, z: 0 })).toEqual({ x: 0, y: 0 });
  });

  test('receding points approach the horizon and never pass it', () => {
    for (const distance of [1_000, 100_000, 10_000_000]) {
      const rise = -projectPoint({ x: -distance, y: -distance, z: 0 }).y;
      expect(rise).toBeLessThan(HORIZON_RISE_PX);
    }
    expect(-projectPoint({ x: -10_000_000, y: -10_000_000, z: 0 }).y)
      .toBeCloseTo(HORIZON_RISE_PX, 0);
  });

  test('height above the floor reads as up the screen and toward the viewer', () => {
    const standing = projectPoint({ x: 0, y: 0, z: CUBE_EDGE_PX });
    expect(standing.y).toBeLessThan(0);
    expect(cameraDepth({ x: 0, y: 0, z: CUBE_EDGE_PX })).toBeGreaterThan(0);
  });

  test('the floor transform the CSS applies is the one this arithmetic describes', () => {
    // The arithmetic still defines floor coverage while CSS applies the same camera to the real cube and
    // the floor. Any drift here would make the coverage proof describe a different view than the browser.
    expect(CAMERA_FLOOR_TRANSFORM).toMatch(/^perspective\(\d+px\) rotateX\(\d+deg\) rotateZ\(\d+deg\)$/);
  });

  test('the exit camera ends directly overhead without changing the shared floor spin', () => {
    expect(CAMERA_FLAT_FLOOR_TRANSFORM)
      .toMatch(/^perspective\(\d+px\) rotateX\(0deg\) rotateZ\(\d+deg\)$/);
    const xStep = projectFlatFloorPoint({ x: CUBE_EDGE_PX, y: 0 });
    const yStep = projectFlatFloorPoint({ x: 0, y: CUBE_EDGE_PX });
    expect(Math.hypot(xStep.x, xStep.y)).toBeCloseTo(CUBE_EDGE_PX, 8);
    expect(Math.hypot(yStep.x, yStep.y)).toBeCloseTo(CUBE_EDGE_PX, 8);
  });

  test('reach is measured from the corners, which is exact for a projective map', () => {
    // A projective map takes lines to lines, so the image of a rectangle is a quadrilateral and its
    // extremes are its vertices. Sampling the boundary densely must therefore find nothing further out.
    const far = 900;
    const near = 400;
    const reach = floorReach(far, near);

    for (let i = 0; i <= 40; i += 1) {
      const t = -far + ((far + near) * i) / 40;
      for (const point of [
        { x: t, y: -far },
        { x: t, y: near },
        { x: -far, y: t },
        { x: near, y: t },
      ]) {
        const projected = projectPoint({ ...point, z: 0 });
        expect(-projected.y).toBeLessThanOrEqual(reach.farRise + 1e-6);
        expect(projected.y).toBeLessThanOrEqual(reach.nearDrop + 1e-6);
        expect(Math.abs(projected.x)).toBeLessThanOrEqual(reach.halfWidth + 1e-6);
      }
    }
  });
});

describe('the cube stands on the floor', () => {
  const mark = splashCubeMarkup();
  const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });

  test('a floor cell is exactly the cube base', () => {
    // Not "about the same size". The cube's footprint has to be one cell of the floor, because that is
    // what makes the lines leaving its base corners the floor's own lines rather than a near miss.
    expect(GROUND_SHAPE.cellPx).toBe(CUBE_EDGE_PX);
  });

  test('the origin is a cell centre, not a cell corner', () => {
    // The cube's base is centred on the origin, so a corner there would leave it straddling four cells.
    const offsetInCells = GROUND_SHAPE.offsetPx / GROUND_SHAPE.cellPx;
    expect(offsetInCells % 1).toBe(0.5);
    expect(Math.floor(offsetInCells)).toBe(GROUND_SHAPE.originCell);
  });

  test('the projected base is asymmetric, which is what proves it is not still isometric', () => {
    const half = CUBE_EDGE_PX / 2;
    const nearCorner = projectPoint({ x: half, y: half, z: 0 });
    const farCorner = projectPoint({ x: -half, y: -half, z: 0 });

    // The near corner reaches further from the origin than the far corner. Under a parallel projection
    // these two distances are equal, and that equality is what made the old floor read as tilting up.
    expect(nearCorner.y).toBeGreaterThan(-farCorner.y);
    // Sideways it stays symmetric, because the spin is 45 degrees.
    expect(projectPoint({ x: half, y: -half, z: 0 }).x)
      .toBeCloseTo(-projectPoint({ x: -half, y: half, z: 0 }).x, 6);
  });

  test('the cube and floor are children of one camera rather than separate projections', () => {
    expect(css).toContain('.pi-splash-camera {');
    expect(css).toContain(`transform: ${CAMERA_FLOOR_TRANSFORM} scale(1);`);
    expect(css).toContain(`transform: translateZ(${CUBE_EDGE_PX / 2}px);`);
    const markRules = css.slice(css.indexOf('.pi-splash-mark {'), css.indexOf('.pi-splash-cube-face {'));
    expect(markRules).not.toContain('translate: -50%');
  });

  test('only the three faces the camera can see are drawn', () => {
    expect(mark.match(/class="pi-splash-cube-face /g) ?? [])
      .toHaveLength(3);
    expect(mark.match(/class="pi-splash-cube-cell"/g) ?? [])
      .toHaveLength(LOGO_GRID_SIZE ** 2 * 2);
  });

  test('the hidden faces are absent, not merely covered', () => {
    expect(mark).not.toContain('face-bottom');
    expect(mark).not.toContain('face-back');
  });

  test('the glyph carries the class the stylesheet animates', () => {
    expect(mark).toContain('class="pi-splash-cube-glyph"');
    expect(css).toContain('.pi-splash-cube-glyph {');
  });
});

describe('the floor covers the window it has to cover', () => {
  // A share of height above the origin, and the rest below, at each window size.
  const VIEWPORTS: ReadonlyArray<readonly [number, number]> = [
    [390, 700],
    [1280, 800],
    [1440, 900],
    [1920, 1080],
  ];

  test.each(VIEWPORTS)('%ix%i: the floor reaches past the sides and the bottom', (width, height) => {
    const originY = height * 0.56;
    expect(GROUND_REACH.halfWidth).toBeGreaterThanOrEqual(width / 2);
    expect(GROUND_REACH.nearDrop).toBeGreaterThanOrEqual(height - originY);
  });

  test('the top is a horizon rather than an edge, and it is faded before it arrives', () => {
    // Reaching the top of a tall window is not merely expensive, it is impossible: receding points crowd
    // toward the horizon. So the floor is faded out before its far edge and the edge never shows.
    expect(GROUND_EDGE_RISE_PX).toBeLessThan(HORIZON_RISE_PX);
    expect(GROUND_FADE_RISE_PX).toBeLessThan(GROUND_EDGE_RISE_PX);

    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    expect(css).toContain('var(--pi-splash-horizon-lift, 0px)');
    expect(css).toContain('.pi-splash-ground-canvas {');
    expect(css).not.toContain('.pi-splash-ground::before {');
  });

  test('the near corner stays in front of the camera', () => {
    // Past the camera plane the projection divides by zero and the image turns inside out. This is the
    // ceiling on how far the floor may extend toward the viewer, and it is easy to cross by accident.
    const ahead = (GROUND_SHAPE.axis - GROUND_SHAPE.originCell - 0.5) * GROUND_SHAPE.cellPx;
    const cameraDistance = Number(/perspective\((\d+)px\)/.exec(CAMERA_FLOOR_TRANSFORM)?.[1]);
    expect(cameraDepth({ x: ahead, y: ahead, z: 0 })).toBeLessThan(cameraDistance);
    expect(GROUND_REACH.nearDrop).toBeGreaterThan(0);
  });

  test('the camera shows the floor instead of grazing it', () => {
    // The first perspective pass put the camera so low that the foreground drop was five times the far
    // reach. The plane was mathematically correct but read as a wall rising toward the viewer.
    expect(GROUND_REACH.farRise).toBeGreaterThan(500);
    expect(GROUND_REACH.nearDrop / GROUND_REACH.farRise).toBeLessThan(4);
  });

  test('tile count grows with the viewport behind one drawing owner', () => {
    const desktop = buildField(1920, 1080).tiles;
    const ultrawide = buildField(5120, 1440).tiles;
    const eightK = buildField(7680, 4320).tiles;
    expect(desktop.length).toBeGreaterThan(0);
    expect(ultrawide.length).toBeGreaterThan(desktop.length);
    expect(eightK.length).toBeGreaterThan(ultrawide.length);
    expect(new Set(eightK.map((tile) => tile.key)).size).toBe(eightK.length);

    // The visual granularity is restored without creating one animated DOM owner per tile. WebGL issues
    // one instanced draw, and Canvas 2D is the renderer fallback when WebGL2 is unavailable.
    const renderer = mountSplashTileCanvas.toString();
    expect(renderer).toContain('drawArraysInstanced');
    expect(renderer).toContain('getContext("2d")');
    expect(renderer).toContain('requestAnimationFrame');
  });

  test('perspective grid lines use screen-space analytic antialiasing', () => {
    const renderer = mountSplashTileCanvas.toString();
    expect(renderer).toContain('fwidth(vUv)');
    expect(renderer).toContain('lineWidthPx = max(projectedLinePx, vec2(uRenderScale))');
    expect(renderer).toContain('densityFade = smoothstep');
    expect(renderer).toContain('coverage * uLine.a');
    expect(renderer).toContain('tile.a * vOpacity');
    expect(renderer).toContain('homogeneousClip.x, -homogeneousClip.y, 0.0, perspectiveW');
    expect(renderer).not.toContain('? uLine : tile');
  });

  test.each([
    [390, 700],
    [1280, 800],
    [2048, 1024],
    [2550, 1275],
    [3840, 2160],
    [5120, 1440],
    [7680, 4320],
  ] as const)('the adaptive overhead field contains every %ix%i viewport corner', (width, height) => {
    const field = buildField(width, height);
    const minX = (field.minCol - 0.5) * CUBE_EDGE_PX;
    const maxX = (field.maxCol + 0.5) * CUBE_EDGE_PX;
    const minY = (field.minRow - 0.5) * CUBE_EDGE_PX;
    const maxY = (field.maxRow + 0.5) * CUBE_EDGE_PX;
    const outline = [
      projectFlatFloorPoint({ x: minX, y: minY }),
      projectFlatFloorPoint({ x: maxX, y: minY }),
      projectFlatFloorPoint({ x: maxX, y: maxY }),
      projectFlatFloorPoint({ x: minX, y: maxY }),
    ];
    const originY = height * SPLASH_GROUND_ORIGIN_Y_PCT / 100;
    const corners = [
      { x: -width / 2, y: -originY },
      { x: width / 2, y: -originY },
      { x: width / 2, y: height - originY },
      { x: -width / 2, y: height - originY },
    ];
    for (const corner of corners) {
      const crosses = outline.map((point, index) => {
        const next = outline[(index + 1) % outline.length] as typeof point;
        return (next.x - point.x) * (corner.y - point.y)
          - (next.y - point.y) * (corner.x - point.x);
      });
      expect(crosses.every((cross) => cross >= -1e-6)).toBe(true);
    }
  });
});

/**
 * The exit is a reveal, not a fade.
 *
 * Each floor cell is opaque, so a cell shrinking away leaves a hole the app shows through, and the
 * staggered delays make that a wave travelling out from the cube's feet. Getting this wrong is silent: an
 * opaque container over the cells produces exactly the same cell animation and reveals nothing, which is
 * what it did before — the lines vanished and the screen stayed flat colour until the element was removed.
 */
describe('the floor is the cover', () => {
  const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });

  test('the Canvas fallback remains opaque without inventing a fake far-field grid', () => {
    expect(css).toContain('.pi-splash-ground-canvas {');
    expect(css).toContain(`background-color: ${PIARIUM_SPLASH_COLORS.background};`);
    expect(css).toContain('.pi-splash-ground-canvas[data-piarium-splash-renderer] {\nbackground: none;');
    expect(css).not.toContain('.pi-splash-ground::before');
  });

  test('the container is not, or the cells would reveal nothing', () => {
    const container = css.slice(css.indexOf('.pi-splash {'), css.indexOf('.pi-splash[data-leaving'));
    expect(container).not.toContain('background');
  });

  test('renderer failure leaves the opaque registered grid in place', () => {
    const fallback = css.slice(
      css.indexOf('.pi-splash-ground-canvas {'),
      css.indexOf('.pi-splash-ground-canvas[data-piarium-splash-renderer]'),
    );
    expect(fallback).toContain(`background-color: ${PIARIUM_SPLASH_COLORS.background};`);
    expect(fallback).not.toContain('background-color: transparent');
  });

  test('the backdrop covers what the floor cannot, and opens from the cube', () => {
    expect(css).toContain(`.pi-splash-backdrop {\nposition: absolute;\ninset: 0;\nbackground: ${PIARIUM_SPLASH_COLORS.background};`);
    expect(css).toContain('@property --pi-splash-open');
    expect(css).toContain(`to { --pi-splash-open: ${GROUND_REVEAL_RADIUS_PX}px; }`);
    // Registered with an initial value of zero and read with a zero fallback, so a browser without
    // @property leaves the backdrop whole rather than leaving a hole in the middle of the cover.
    expect(css).toContain('initial-value: 0px;');
    expect(css).toContain('var(--pi-splash-open, 0px)');
  });

  test('the hole stops inside the region the cells actually pave at full opacity', () => {
    // Two independent bounds, and the reveal has to respect the smaller. Past the floor's outline there
    // are no cells to reveal through; past the horizon ramp the cells are no longer opaque.
    const inscribed = floorInscribedRadius(
      GROUND_SHAPE.offsetPx,
      (GROUND_SHAPE.axis - GROUND_SHAPE.originCell - 0.5) * GROUND_SHAPE.cellPx,
    );
    expect(GROUND_REVEAL_RADIUS_PX).toBeLessThanOrEqual(inscribed);
    expect(GROUND_REVEAL_RADIUS_PX).toBeLessThanOrEqual(GROUND_FADE_RISE_PX);
    expect(GROUND_REVEAL_RADIUS_PX).toBeGreaterThan(CUBE_EDGE_PX);
  });

  test('the peripheral falloff hands off once instead of rerasterizing the floor every frame', () => {
    // The backdrop hides the handoff after the camera reaches its endpoint. A discrete mask change avoids
    // invalidating the large screen-space mask every frame while preserving the atmospheric wait state.
    expect(css).toContain('@property --pi-splash-floor-mask');
    expect(css).toContain('rgba(0,0,0,1) var(--pi-splash-floor-mask');
    expect(css).toContain('--pi-splash-floor-mask: 160vmax;');
    expect(css).toContain('pi-splash-floor-unmask');
    expect(css).toContain('steps(1, end) both;');
  });

  test('the backdrop finishes fading before the last cells do', () => {
    // So the outermost cells are seen coming apart against the app rather than against flat colour.
    const [, fadeMs, delayMs] = /pi-splash-backdrop-out (\d+)ms (\d+)ms/.exec(css)
      ?.map(Number) as [number, number, number];
    const [, openMs] = /pi-splash-open (\d+)ms/.exec(css)?.map(Number) as [number, number];
    expect(delayMs).toBeGreaterThanOrEqual(openMs);
    expect(delayMs + fadeMs).toBeLessThan(SPLASH_EXIT_DURATION_MS);
  });

  test('the reveal is boot-only, and boot is what a host gets by saying nothing', () => {
    // A profile switch sweeps its cells along one axis, so a hole opening from the middle would travel the
    // wrong way. The three hosts that paint pre-module set no mode and must still get the reveal.
    expect(css).toContain(".pi-splash:not([data-mode='switch'])[data-leaving='true'] .pi-splash-backdrop {\nanimation:\npi-splash-open");
    expect(css).toContain(".pi-splash[data-mode='switch'][data-leaving='true'] .pi-splash-backdrop {\nanimation: pi-splash-backdrop-out");
    for (const body of [readWebShell(), readMiniChat(), readWebview()]) {
      const open = body.indexOf(`<div id="${INITIAL_SPLASH_IDS.root}"`);
      expect(open).toBeGreaterThan(-1);
      expect(body.slice(open, body.indexOf('>', open))).not.toContain('data-mode');
    }
  });
});

describe('exit choreography', () => {
  test('boot starts at the tile under the cube and ends at the far corner', () => {
    const field = buildField();
    const tiles = field.tiles;
    const atCube = tiles.find((tile) => tile.key === '0:0');
    const delays = tiles.map((tile) => tile.delayMs);

    expect(atCube?.delayMs).toBe(0);
    expect(Math.min(...delays)).toBe(0);
    const furthest = tiles.reduce((best, tile) => (
      Math.hypot(tile.xPx, tile.yPx) > Math.hypot(best.xPx, best.yPx) ? tile : best
    ));
    expect(furthest?.delayMs).toBe(Math.max(...delays));
    expect(atCube?.scatterXPx).toBe(0);
    expect(atCube?.scatterYPx).toBe(0);
    expect(tiles.find((tile) => tile.key === '0:1')?.scatterXPx)
      .toBeGreaterThan(0);
    expect(tiles.find((tile) => tile.key === '-1:0')?.scatterYPx)
      .toBeLessThan(0);
  });

  test('switch reverses with the direction', () => {
    const forwardField = buildField(1920, 1080, { mode: 'switch', direction: 'forward' });
    const backwardField = buildField(1920, 1080, { mode: 'switch', direction: 'backward' });
    const forward = forwardField.tiles;
    const backward = backwardField.tiles;

    const column = (cells: typeof forward, index: number): number[] =>
      cells.filter((cell) => cell.xPx === index * CUBE_EDGE_PX).map((cell) => cell.delayMs);

    expect(Math.min(...column(forward, forwardField.minCol)))
      .toBeLessThan(Math.min(...column(forward, forwardField.maxCol)));
    expect(Math.min(...column(backward, backwardField.maxCol)))
      .toBeLessThan(Math.min(...column(backward, backwardField.minCol)));
    expect(forward.every((cell) => cell.scatterXPx > 0 && cell.scatterYPx === 0)).toBe(true);
    expect(backward.every((cell) => cell.scatterXPx < 0 && cell.scatterYPx === 0)).toBe(true);
  });

  test('tile playback stays in one Canvas rather than rebuilding DOM paint owners', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    const renderer = mountSplashTileCanvas.toString();
    expect(css).not.toContain('.pi-splash-tile-cluster');
    expect(renderer).toContain('tile.scatterXPx * motion.eased');
    expect(renderer).toContain('frame.scale = mix(1, 0.56, motion.eased)');
    expect(renderer).toContain('frame.opacity =');
  });

  test('boot presses the cube into its registered footprint before the floor opens', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    expect(css).toContain('@keyframes pi-splash-mark-press');
    const press = css.slice(
      css.indexOf('@keyframes pi-splash-mark-press'),
      css.indexOf('@keyframes pi-splash-cube-bury'),
    );
    expect(press).toContain(`translateZ(${CUBE_EDGE_PX / 2}px)`);
    expect(press).toContain(`translateZ(${-CUBE_EDGE_PX / 2}px)`);
    expect(press).not.toContain('translateY');
    // Animating opacity on this preserve-3d parent makes Chromium flatten its faces before it moves.
    expect(press).not.toContain('opacity');
    expect(press).not.toContain('scaleX');
    expect(press).not.toContain('scaleY');
    expect(css).toContain('@keyframes pi-splash-camera-flatten');
    expect(css).toContain(CAMERA_PRESS_FLOOR_TRANSFORM);
    expect(css).toContain(CAMERA_FLAT_FLOOR_TRANSFORM);
    expect(css).toContain(`100% { transform: ${CAMERA_FLAT_FLOOR_TRANSFORM} scale(1); }`);
    const centre = buildField().tiles.find((tile) => tile.key === '0:0');
    expect(centre).toMatchObject({ delayMs: 0, scatterXPx: 0, scatterYPx: 0 });
  });

  test('the camera preserves enough angle for the rigid press to travel on screen', () => {
    const timing = splashTilePlaybackTiming('standard');
    const tilt = SPLASH_CAMERA_PRESS_TILT_DEG * Math.PI / 180;
    const cubeCentre = CUBE_EDGE_PX / 2;
    const pressStartY = -cubeCentre * Math.sin(tilt)
      / (1 - cubeCentre * Math.cos(tilt) / SPLASH_CAMERA_DISTANCE_PX);
    const previousRigidPress = Math.abs(projectPoint({
      x: 0,
      y: 0,
      z: -CUBE_EDGE_PX * 0.22,
    }).y);

    // The first camera leg retains the accepted visible press distance; the second leg ends with the
    // cube's full burial and the centre tile release, so the Z motion is never hidden by an early top view.
    expect(Math.abs(pressStartY)).toBeGreaterThanOrEqual(previousRigidPress);
    expect(timing.cameraKneeProgress).toBeGreaterThan(0);
    expect(timing.cameraKneeProgress).toBeLessThan(1);
    expect(timing.cameraDelayMs + timing.cameraDurationMs).toBe(timing.releaseMs);

    const renderer = mountSplashTileCanvas.toString();
    expect(renderer).toContain('forwardProgress <= knee');
    expect(renderer).toContain('options.camera.pressTiltDeg');
  });

  test('the contact footprint flashes solid and sends a short floor-space echo', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    const contact = css.slice(
      css.indexOf('@keyframes pi-splash-contact-press'),
      css.indexOf('@keyframes pi-splash-mark-out'),
    );
    expect(contact).toContain(`background: ${PIARIUM_SPLASH_COLORS.stroke};`);
    expect(contact).toContain('transform: scale(0.82);');
    expect(contact).toContain('transform: scale(1.28);');
    expect(contact).toContain('0 0 0 18px transparent');
  });

  test('the buried cube is gone before the centre floor cell opens', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    const [, faceDurationMs] = /pi-splash-cube-bury (\d+)ms/.exec(css)
      ?.map(Number) as [number, number];
    const bury = css.slice(
      css.indexOf('@keyframes pi-splash-cube-bury'),
      css.indexOf('@keyframes pi-splash-contact-press'),
    );
    const [, hiddenPct] = /(\d+)%, 100% \{ opacity: 0; \}/.exec(bury)
      ?.map(Number) as [number, number];
    const tileReleaseMs = splashTilePlaybackTiming('standard').releaseMs;

    expect(faceDurationMs * hiddenPct / 100).toBeLessThan(tileReleaseMs);
    expect(css).toContain(".pi-splash[data-leaving='true'] .pi-splash-cube-glyph {\nanimation: none;");

    const [, contactDurationMs, contactDelayMs] = /pi-splash-contact-press (\d+)ms (\d+)ms/
      .exec(css)?.map(Number) as [number, number, number];
    expect(contactDelayMs + contactDurationMs).toBe(tileReleaseMs);
  });

  test('the waiting pulse is drawn on the cube footprint in floor space', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    expect(css).toContain(
      ".pi-splash:not([data-mode='switch']) .pi-splash-ground::after,\n.pi-splash[data-mode='switch'][data-phase] .pi-splash-ground::after {",
    );
    expect(css).toContain(`left: ${GROUND_SHAPE.offsetPx - CUBE_EDGE_PX / 2}px;`);
    expect(css).toContain(`top: ${GROUND_SHAPE.offsetPx - CUBE_EDGE_PX / 2}px;`);
    expect(css).toContain('animation: pi-splash-contact-pulse 1.8s ease-in-out infinite;');
  });

  test('every delay stays within the budget the exit duration is built from', () => {
    for (const mode of ['boot', 'switch'] as const) {
      for (const cell of buildField(5120, 1440, { mode }).tiles) {
        expect(cell.delayMs).toBeGreaterThanOrEqual(0);
        expect(cell.delayMs).toBeLessThanOrEqual(520);
      }
    }
  });

  test('workbench covering is the exact time reversal of revealing at both tempos', () => {
    const cells = buildField(1920, 1080, { mode: 'switch' }).tiles;
    for (const tempo of ['quick', 'standard'] as const) {
      const timings = cells.map((cell) => splashWorkbenchTileDelays(cell.delayMs, tempo));
      const mirroredSums = new Set(timings.map((timing) => timing.coverDelayMs + timing.revealDelayMs));
      expect(mirroredSums.size).toBe(1);
      const firstReveal = timings.reduce((best, timing) => (
        timing.revealDelayMs < best.revealDelayMs ? timing : best
      ));
      const firstCover = timings.reduce((best, timing) => (
        timing.coverDelayMs < best.coverDelayMs ? timing : best
      ));
      expect(firstReveal.coverDelayMs).toBeGreaterThan(firstCover.coverDelayMs);
      expect(firstCover.revealDelayMs).toBeGreaterThan(firstReveal.revealDelayMs);
    }
  });

  test('quick workbench playback keeps every phase but uses the accepted sweep duration', () => {
    expect(splashWorkbenchPhaseDurationMs('quick')).toBe(SPLASH_WORKBENCH_QUICK_DURATION_MS);
    expect(splashWorkbenchPhaseDurationMs('standard')).toBe(SPLASH_EXIT_DURATION_MS);
    expect(splashWorkbenchPhaseDurationMs('quick', true)).toBe(SPLASH_REDUCED_EXIT_DURATION_MS);

    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    expect(css).toContain("[data-phase='covering'][data-tempo='quick'] .pi-splash-mark {");
    expect(css).toContain('pi-splash-mark-press 525ms 515ms cubic-bezier(0.3, 0, 0.2, 1) reverse both;');
    expect(css).toContain("[data-phase='revealing'][data-tempo='quick'] .pi-splash-mark {");
    expect(css).toContain('animation-duration: 1040ms;');
    expect(css).toContain('animation-name: pi-splash-cover-clock;');
    expect(css).toContain('animation-name: pi-splash-reveal-clock;');
  });

  test('the built-in extension declares the exact duration of the scene it renders', () => {
    const contribution = PIARIUM_BUILTIN_TRANSITION_SCENE_EXTENSION.manifest.contributions?.[0];
    expect(contribution?.kind).toBe('transition-scene');
    const data = parsePiariumTransitionSceneContributionData(contribution?.data);
    for (const phase of ['covering', 'revealing'] as const) {
      for (const tempo of ['quick', 'standard'] as const) {
        expect(piariumTransitionSceneDuration(data, {
          phase,
          reducedMotion: false,
          scene: PIARIUM_WORKBENCH_PROFILE_TRANSITION_SCENE,
          tempo,
        })).toBe(splashWorkbenchPhaseDurationMs(tempo));
      }
      expect(piariumTransitionSceneDuration(data, {
        phase,
        reducedMotion: true,
        scene: PIARIUM_WORKBENCH_PROFILE_TRANSITION_SCENE,
        tempo: 'standard',
      })).toBe(SPLASH_REDUCED_EXIT_DURATION_MS);
    }
  });

  test('breathing is opt-in, deterministic, and reaches the real far tiles', () => {
    const none = buildField(5120, 1440, { breatheShare: 0 }).tiles;
    expect(none.every((cell) => cell.breatheDelayMs === null)).toBe(true);

    const all = buildField(5120, 1440, { breatheShare: 1 }).tiles;
    expect(all.every((cell) => cell.breatheDelayMs !== null)).toBe(true);
    const farRadius = Math.max(...all.map((cell) => Math.hypot(cell.xPx, cell.yPx)));
    expect(all.filter((cell) => Math.hypot(cell.xPx, cell.yPx) === farRadius)
      .every((cell) => cell.breatheDelayMs !== null)).toBe(true);

    const normal = buildField(5120, 1440, { breatheShare: 0.1 }).tiles;
    expect(normal).toEqual(buildField(5120, 1440, { breatheShare: 0.1 }).tiles);
    expect(normal.some((cell) => (
      cell.yPx < -GROUND_SHAPE.originCell * CUBE_EDGE_PX && cell.breatheDelayMs !== null
    ))).toBe(true);
  });
});

/**
 * Four surfaces paint this splash: the web shell, the mini-chat window, the VS Code webview, and the React
 * component. They differ in what they show and where their colours come from, and those differences are
 * deliberate. What must not differ is the camera and the exit contract, because a floor on a different
 * camera stops meeting the cube, and a different exit attribute means the shared dismissal silently does
 * nothing.
 */
describe('every splash host carries the same generated bytes', () => {
  test('the web shell embeds the generated rules character for character', () => {
    // Not a similarity check. Perspective rules are fiddly enough that an approximate copy is worse than
    // none: it would look almost right and diverge silently.
    expect(between(readWebShell(), ...CSS_SENTINELS))
      .toBe(splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true }).trim());
  });

  test('the web shell embeds the shared-camera cube character for character', () => {
    expect(between(readWebShell(), ...MARK_SENTINELS))
      .toBe(splashCubeMarkup());
  });

  test('the mini-chat window embeds the no-cube variant character for character', () => {
    expect(between(readMiniChat(), ...CSS_SENTINELS))
      .toBe(splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: false }).trim());
  });

  test('both pre-paint hosts embed the same adaptive floor runtime', () => {
    // Function.toString() formatting differs between Bun (the emitter) and Vitest's transform. The two
    // shipped projections must still be byte-identical to each other, while the next test checks the live
    // generator's semantic contract.
    const webRuntime = between(readWebShell(), ...JS_SENTINELS);
    const miniRuntime = between(readMiniChat(), ...JS_SENTINELS);
    expect(webRuntime).toBe(miniRuntime);
    expect(webRuntime).toContain('inverseProject');
    expect(webRuntime).toContain('drawArraysInstanced');
  });

  test('the full pre-paint host exposes its stylesheet for later scene mounts to reuse', () => {
    expect(readWebShell()).toContain(`<style id="${PIARIUM_SPLASH_STYLE_ELEMENT_ID}">`);
    expect(readMiniChat()).toContain('<style id="piarium-splash-styles-no-mark">');
  });

  test('the generated floor script builds its tile field from the live viewport', () => {
    const script = splashGroundScript(INITIAL_SPLASH_IDS.ground);
    expect(script).toContain(`getElementById(${JSON.stringify(INITIAL_SPLASH_IDS.ground)})`);
    expect(script).toContain("createElement('canvas')");
    expect(script).toContain('inverseProject');
    expect(script).toContain('viewportWidth');
    expect(script).toContain('addEventListener("resize"');
    expect(script).toContain('drawArraysInstanced');
    expect(script).toContain('getContext("2d")');
    expect(script).toContain("data-piarium-splash-renderer");
    expect(script).not.toContain('pi-splash-tile-cluster');
    // Raw trigonometric tails differ across platform math libraries and would make generated HTML drift.
    expect(script).not.toMatch(/\d+\.\d{7,}/);
  });

  test('the generated floor script is stable across calls', () => {
    // It picks breathing cells at random, which would otherwise churn the embedded copies on every
    // regeneration and fail the verbatim assertions for no reason.
    expect(splashGroundScript('x')).toBe(splashGroundScript('x'));
  });

  test('the VS Code webview generates its rules and its cube instead of embedding them', () => {
    // It builds its document as text at runtime, so it can call the generators. A copy here would mean
    // the duplication grew rather than shrank.
    const source = readWebview();
    expect(source).toContain('splashPlaneCss(');
    expect(source).toContain('splashGroundScript(');
    expect(source).toContain('splashCubeMarkup(');
    expect(source).not.toContain(CSS_SENTINELS[0]);
    expect(source).not.toContain('<svg');
  });

  test('the pre-paint hosts carry the generated camera rather than a handwritten projection', () => {
    for (const body of [readWebShell(), readMiniChat()]) {
      expect(body).toContain(CAMERA_FLOOR_TRANSFORM);
      expect(body).toContain('class="pi-splash-camera"');
      expect(body).toContain('inverseProject');
      expect(body).not.toContain('matrix(0.866');
    }
  });

  const hosts: ReadonlyArray<{ name: string; read: () => string }> = [
    { name: 'web shell', read: readWebShell },
    { name: 'mini-chat window', read: readMiniChat },
    { name: 'VS Code webview', read: readWebview },
  ];

  for (const host of hosts) {
    test(`${host.name} tells the cover to leave through the shared attribute`, () => {
      expect(host.read()).toContain(INITIAL_SPLASH_IDS.leavingAttribute);
    });

    test(`${host.name} puts the backdrop under the floor, and the floor inside both fades`, () => {
      // Backdrop first so the cells paint over it; then the screen-space falloff, then the horizon ramp,
      // then the floor. Masking the floor itself is what cut the screen's corners first in an earlier
      // attempt, and a backdrop painted after the cells would cover the holes they leave.
      const body = host.read();
      const root = body.indexOf(`<div id="${INITIAL_SPLASH_IDS.root}"`);
      const backdrop = body.indexOf('class="pi-splash-backdrop"', root);
      const clip = body.indexOf('class="pi-splash-ground-clip"', root);
      const horizon = body.indexOf('class="pi-splash-horizon"', root);
      const camera = body.indexOf('class="pi-splash-camera"', root);
      const ground = body.indexOf('class="pi-splash-ground"', root);
      expect(backdrop).toBeGreaterThan(-1);
      expect(clip).toBeGreaterThan(backdrop);
      expect(horizon).toBeGreaterThan(clip);
      expect(camera).toBeGreaterThan(horizon);
      expect(ground).toBeGreaterThan(camera);
    });

    test(`${host.name} keeps the splash out of React's container`, () => {
      // The regression that made every other part of this pointless. `createRoot()` empties its container
      // on the first commit, so a splash inside #root was deleted the instant React mounted: the exit
      // never ran, dismissInitialSplash() found nothing, and the status line went nowhere. Sibling, and
      // ahead of #root so it paints as early as the parser reaches it.
      const body = host.read();
      const splash = body.indexOf(`id="${INITIAL_SPLASH_IDS.root}"`);
      const container = body.indexOf('id="root"');
      expect(splash).toBeGreaterThan(-1);
      expect(container).toBeGreaterThan(splash);
    });
  }

  test('the web shell keeps the ids the app reaches for', () => {
    // `lib/splash.ts` can only address this markup through the DOM, so a rename here would stop every
    // status message appearing instead of failing anywhere a reader would notice.
    const html = readWebShell();
    expect(html).toContain(`id="${INITIAL_SPLASH_IDS.root}"`);
    expect(html).toContain(`id="${INITIAL_SPLASH_IDS.status}"`);
    expect(html).toContain(`id="${INITIAL_SPLASH_IDS.ground}"`);
  });

  test('the status line is a sibling of the cube, not the element the cube lives in', () => {
    // The regression this guards: two call sites used to assign textContent on the container, which
    // deleted the cube's SVG and left a bare sentence on a coloured field.
    const html = readWebShell();
    expect(html.indexOf(`id="${INITIAL_SPLASH_IDS.status}"`))
      .toBeGreaterThan(html.indexOf(MARK_SENTINELS[1]));
  });

  test('the mini-chat window deliberately carries no cube', () => {
    // Its content renders the single Piarium cube in its empty state, so a cube here would show a second
    // one for a moment before handing off.
    const html = readMiniChat();
    expect(html).not.toContain('pi-splash-mark');
    expect(html).not.toContain(MARK_SENTINELS[0]);
  });

  test('the mini-chat safety dismissal keeps the cover through the full staged exit', () => {
    expect(readMiniChat()).toContain(
      `setTimeout(function () { loading.remove(); }, ${SPLASH_EXIT_DURATION_MS});`,
    );
  });

  test('reduced motion keeps the cover visible', () => {
    // It must weaken the animation, not remove the cover: hiding it would put the unpainted first frame
    // back, which is the problem the splash exists to solve.
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: true });
    expect(css).toContain('prefers-reduced-motion');
    expect(css).not.toMatch(/prefers-reduced-motion[\s\S]*display:\s*none/);
    expect(css).toContain('.pi-splash-cube-glyph,');
  });

  test('the cover is opaque even with no cube on it, since a transparent one hides nothing', () => {
    const css = splashPlaneCss(PIARIUM_SPLASH_COLORS, { withMark: false });
    expect(css).toContain(`.pi-splash-backdrop {\nposition: absolute;\ninset: 0;\nbackground: ${PIARIUM_SPLASH_COLORS.background};`);
    expect(css).toContain('.pi-splash-ground-canvas {');
    expect(css).toContain(`background-color: ${PIARIUM_SPLASH_COLORS.background};`);
  });
});
