import { type PiariumExtensionActualState, type PiariumExtensionAssetPayload, type PiariumExtensionAssetRequest, type PiariumExtensionCandidateCapabilityReviewRequest, type PiariumExtensionCandidatePreparationResult, type PiariumExtensionCandidateSelectionRequest, type PiariumExtensionCatalogAvailability, type PiariumExtensionCatalogDocument, type PiariumExtensionCatalogSnapshot, type PiariumExtensionCapabilityReviewRequest, type PiariumExtensionHostIdentityDocument, type PiariumExtensionHostStateSnapshot, type PiariumExtensionHostStateWaitRequest, type PiariumExtensionInstallationRecord, type PiariumExtensionManifest, type PiariumExtensionManagedEntrypointPayload, type PiariumExtensionManagedEntrypointRequest, type PiariumExtensionLocalSourceReloadRequest, type PiariumExtensionLocalSourceReloadResult, type PiariumExtensionPackageSource, type PiariumExtensionPackageInstallRequest, type PiariumExtensionRemoveRequest, type PiariumExtensionServiceCatalogSnapshot, type PiariumExtensionServiceInvocationRequest, type PiariumExtensionServiceSelectionRequest, type PiariumExtensionStorageAddress, type PiariumExtensionStorageOpenRequest, type PiariumExtensionStorageSnapshot } from "./types.js";
export declare class PiariumExtensionContractError extends Error {
    readonly issues: string[];
    constructor(message: string, issues: string[]);
}
export declare function isRecord(value: unknown): value is Record<string, unknown>;
export declare function parsePiariumExtensionManifest(value: unknown): PiariumExtensionManifest;
export declare function assertPiariumApplicationVersion(piariumVersion: string): void;
export declare function assertPiariumExtensionManifestCompatibility(manifest: PiariumExtensionManifest, piariumVersion: string): void;
export declare function parsePiariumExtensionInstallationRecord(value: unknown, path?: string): PiariumExtensionInstallationRecord;
export declare function parsePiariumExtensionCatalogDocument(value: unknown): PiariumExtensionCatalogDocument;
export declare function parsePiariumExtensionHostIdentityDocument(value: unknown): PiariumExtensionHostIdentityDocument;
export declare function parsePiariumExtensionCatalogSnapshot(value: unknown): PiariumExtensionCatalogSnapshot;
export declare function parsePiariumExtensionCatalogAvailability(value: unknown): PiariumExtensionCatalogAvailability;
export declare function isPiariumExtensionId(value: string): boolean;
export declare function parsePiariumExtensionAssetRequest(value: unknown): PiariumExtensionAssetRequest;
export declare function parsePiariumExtensionManagedEntrypointRequest(value: unknown): PiariumExtensionManagedEntrypointRequest;
export declare function parsePiariumExtensionAssetPayload(value: unknown): PiariumExtensionAssetPayload;
export declare function parsePiariumExtensionManagedEntrypointPayload(value: unknown): PiariumExtensionManagedEntrypointPayload;
export declare function parsePiariumExtensionCandidateSelectionRequest(value: unknown): PiariumExtensionCandidateSelectionRequest;
export declare function parsePiariumExtensionCandidateCapabilityReviewRequest(value: unknown): PiariumExtensionCandidateCapabilityReviewRequest;
export declare function parsePiariumExtensionCapabilityReviewRequest(value: unknown): PiariumExtensionCapabilityReviewRequest;
export declare function parsePiariumExtensionPackageSource(value: unknown): PiariumExtensionPackageSource;
export declare function parsePiariumExtensionPackageInstallRequest(value: unknown): PiariumExtensionPackageInstallRequest;
export declare function parsePiariumExtensionLocalSourceReloadRequest(value: unknown): PiariumExtensionLocalSourceReloadRequest;
export declare function parsePiariumExtensionLocalSourceReloadResult(value: unknown): PiariumExtensionLocalSourceReloadResult;
export declare function parsePiariumExtensionRemoveRequest(value: unknown): PiariumExtensionRemoveRequest;
export declare function parsePiariumExtensionActualState(value: unknown): PiariumExtensionActualState;
export declare function parsePiariumExtensionCandidatePreparationResult(value: unknown): PiariumExtensionCandidatePreparationResult;
export declare function parsePiariumExtensionServiceCatalogSnapshot(value: unknown): PiariumExtensionServiceCatalogSnapshot;
export declare function parsePiariumExtensionServiceInvocationRequest(value: unknown): PiariumExtensionServiceInvocationRequest;
export declare function parsePiariumExtensionServiceSelectionRequest(value: unknown): PiariumExtensionServiceSelectionRequest;
export declare function parsePiariumExtensionHostStateWaitRequest(value: unknown): PiariumExtensionHostStateWaitRequest;
export declare function parsePiariumExtensionHostStateSnapshot(value: unknown): PiariumExtensionHostStateSnapshot;
export declare function parsePiariumExtensionStorageOpenRequest(value: unknown): PiariumExtensionStorageOpenRequest;
export declare function parsePiariumExtensionStorageAddress(value: unknown): PiariumExtensionStorageAddress;
export declare function parsePiariumExtensionStorageSnapshot(value: unknown): PiariumExtensionStorageSnapshot;
//# sourceMappingURL=validation.d.ts.map