import { type JsonValue, type PiariumExtensionActivationEvent, type PiariumExtensionActualState, type PiariumExtensionCandidateCapabilityReviewRequest, type PiariumExtensionCandidateSelectionRequest, type PiariumExtensionCapabilityReviewRequest, type PiariumExtensionCandidatePreparationResult, type PiariumExtensionCatalogSnapshot, type PiariumExtensionHostStateSnapshot, type PiariumExtensionHostStateWaitRequest, type PiariumExtensionLocalSourceReloadRequest, type PiariumExtensionLocalSourceReloadResult, type PiariumExtensionPackageInstallRequest, type PiariumExtensionRemoveRequest, type PiariumExtensionServiceInvocationRequest, type PiariumExtensionServiceRoutingRuleRemoveRequest, type PiariumExtensionServiceRoutingRuleUpdateRequest, type PiariumExtensionServiceRoutingSnapshot, type PiariumExtensionServiceSelectionRequest, type PiariumWorkbenchLayoutUpdateRequest, type PiariumWorkbenchProfileRemoveRequest, type PiariumWorkbenchProfileApplyRequest, type PiariumWorkbenchProfileSelectionRequest, type PiariumWorkbenchProfileSnapshot, type PiariumWorkbenchProfileUpsertRequest } from "@piarium/extension-contract";
import { ApplicationExtensionCatalog } from "./application-catalog.js";
import { BrokeredHostSupervisor, type BrokeredHostTransportFactory } from "./broker-supervisor.js";
import { HostCapabilityRegistry } from "./capability-registry.js";
import { ExtensionPackageManager } from "./package-manager.js";
import { HostServiceRegistry } from "./service-registry.js";
import { ServiceRoutingStore } from "./service-routing-store.js";
import { ExtensionStorageStore } from "./storage-store.js";
import { WorkbenchProfileStore } from "./workbench-profile-store.js";
export interface ApplicationExtensionRuntimeOptions {
    brokerScript: string;
    capabilities?: HostCapabilityRegistry;
    catalog?: ApplicationExtensionCatalog;
    dataDir: string;
    packages?: ExtensionPackageManager;
    piariumVersion: string;
    routing?: ServiceRoutingStore;
    services?: HostServiceRegistry;
    storage?: ExtensionStorageStore;
    transportFactory?: BrokeredHostTransportFactory;
    workbench?: WorkbenchProfileStore;
}
export declare class ApplicationExtensionRuntime {
    #private;
    readonly capabilities: HostCapabilityRegistry;
    readonly catalog: ApplicationExtensionCatalog;
    readonly packages: ExtensionPackageManager;
    readonly piariumVersion: string;
    readonly routing: ServiceRoutingStore;
    readonly services: HostServiceRegistry;
    readonly storage: ExtensionStorageStore;
    readonly supervisor: BrokeredHostSupervisor;
    readonly workbench: WorkbenchProfileStore;
    private constructor();
    static create(options: ApplicationExtensionRuntimeOptions): Promise<ApplicationExtensionRuntime>;
    start(): Promise<PiariumExtensionHostStateSnapshot>;
    state(): Promise<PiariumExtensionHostStateSnapshot>;
    subscribe(listener: () => void): () => void;
    waitForState(requestValue: PiariumExtensionHostStateWaitRequest | unknown, signal?: AbortSignal): Promise<PiariumExtensionHostStateSnapshot>;
    reconcile(snapshot?: PiariumExtensionCatalogSnapshot): Promise<void>;
    installOrStage(requestValue: PiariumExtensionPackageInstallRequest | unknown, signal?: AbortSignal): Promise<PiariumExtensionCatalogSnapshot>;
    reloadLocalSource(requestValue: PiariumExtensionLocalSourceReloadRequest | unknown, signal?: AbortSignal): Promise<PiariumExtensionLocalSourceReloadResult>;
    removeExtension(requestValue: PiariumExtensionRemoveRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    setEnabled(extensionId: string, enabled: boolean, expectedRevision: number): Promise<PiariumExtensionCatalogSnapshot>;
    setAllEnabled(enabled: boolean, expectedRevision: number): Promise<PiariumExtensionCatalogSnapshot>;
    prepareCandidate(extensionId: string, integrity: string): Promise<PiariumExtensionCandidatePreparationResult>;
    activateExtension(extensionId: string): Promise<void>;
    activateForEvent(event: PiariumExtensionActivationEvent): Promise<void>;
    discardPreparedCandidate(extensionId: string, integrity: string): Promise<void>;
    discardCandidate(requestValue: PiariumExtensionCandidateSelectionRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    selectCandidate(requestValue: PiariumExtensionCandidateSelectionRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    requestCandidateApplication(requestValue: PiariumExtensionCandidateSelectionRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    reviewCandidateCapabilities(requestValue: PiariumExtensionCandidateCapabilityReviewRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    reviewCapabilities(requestValue: PiariumExtensionCapabilityReviewRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    reportActualState(extensionId: string, stateValue: PiariumExtensionActualState | unknown): Promise<void>;
    invokeService(request: PiariumExtensionServiceInvocationRequest | unknown, signal?: AbortSignal): Promise<JsonValue>;
    setServiceSelection(requestValue: PiariumExtensionServiceSelectionRequest | unknown): Promise<PiariumExtensionHostStateSnapshot>;
    upsertServiceRoutingRule(request: PiariumExtensionServiceRoutingRuleUpdateRequest | unknown): Promise<PiariumExtensionServiceRoutingSnapshot>;
    removeServiceRoutingRule(request: PiariumExtensionServiceRoutingRuleRemoveRequest | unknown): Promise<PiariumExtensionServiceRoutingSnapshot>;
    updateWorkbenchLayout(request: PiariumWorkbenchLayoutUpdateRequest | unknown): Promise<PiariumWorkbenchProfileSnapshot>;
    selectWorkbenchProfile(request: PiariumWorkbenchProfileSelectionRequest | unknown): Promise<PiariumWorkbenchProfileSnapshot>;
    upsertWorkbenchProfile(request: PiariumWorkbenchProfileUpsertRequest | unknown): Promise<PiariumWorkbenchProfileSnapshot>;
    removeWorkbenchProfile(request: PiariumWorkbenchProfileRemoveRequest | unknown): Promise<PiariumWorkbenchProfileSnapshot>;
    applyWorkbenchProfile(requestValue: PiariumWorkbenchProfileApplyRequest | unknown): Promise<PiariumExtensionCatalogSnapshot>;
    stop(): Promise<void>;
}
//# sourceMappingURL=application-runtime.d.ts.map